import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {flex: 1},
  header: {
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 6,
    paddingHorizontal: 4,
  },
  summaryText: {fontSize: 12, lineHeight: 17},
  updateText: {fontSize: 11, lineHeight: 16},
  legend: {flexDirection: 'row', flexWrap: 'wrap', gap: 14, marginTop: 8, paddingHorizontal: 4},
  legendItem: {flexDirection: 'row', alignItems: 'center', gap: 6},
  legendDot: {width: 9, height: 9, borderRadius: 5},
  legendText: {fontSize: 10, lineHeight: 15},
  inlineError: {marginTop: 7, paddingHorizontal: 4, fontSize: 11, lineHeight: 16},
  map: {flex: 1},
  centered: {flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 28},
  stateTitle: {fontSize: 16, lineHeight: 22, fontWeight: '700', textAlign: 'center'},
  stateText: {marginTop: 7, fontSize: 13, lineHeight: 19, textAlign: 'center'},
  retryButton: {marginTop: 16, paddingHorizontal: 18, paddingVertical: 10, borderRadius: 10},
  retryText: {fontSize: 13, lineHeight: 18, fontWeight: '700'},
  marker: {
    minWidth: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
    borderWidth: 2,
    borderRadius: 16,
  },
  markerText: {fontSize: 10, lineHeight: 14, fontWeight: '800'},
  cluster: {
    minWidth: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 7,
    borderWidth: 2,
    borderRadius: 18,
  },
  clusterText: {fontSize: 11, lineHeight: 15, fontWeight: '800'},
  emptyOverlay: {
    position: 'absolute',
    left: 20,
    right: 20,
    top: 20,
    padding: 14,
    borderRadius: 10,
    borderWidth: StyleSheet.hairlineWidth,
  },
  emptyTitle: {fontSize: 13, lineHeight: 18, fontWeight: '700'},
  emptyText: {marginTop: 2, fontSize: 11, lineHeight: 16},
  modal: {flex: 1, justifyContent: 'flex-end'},
  backdrop: {...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0, 0, 0, 0.38)'},
  sheet: {maxHeight: '62%', borderTopLeftRadius: 16, borderTopRightRadius: 16, paddingTop: 8},
  handle: {alignSelf: 'center', width: 36, height: 4, borderRadius: 2, marginBottom: 10},
  sheetHeader: {paddingHorizontal: 18, paddingBottom: 10},
  sheetTitle: {fontSize: 16, lineHeight: 22, fontWeight: '700'},
  sheetSubtitle: {marginTop: 2, fontSize: 11, lineHeight: 16},
  groupItem: {paddingHorizontal: 18, paddingVertical: 11, borderTopWidth: StyleSheet.hairlineWidth},
  groupName: {fontSize: 13, lineHeight: 18, fontWeight: '700'},
  groupDetails: {marginTop: 3, fontSize: 11, lineHeight: 16},
  closeSheet: {alignSelf: 'flex-end', marginHorizontal: 18, marginTop: 8, paddingHorizontal: 4, paddingVertical: 9},
  closeSheetText: {fontSize: 13, lineHeight: 18, fontWeight: '700'},
});

export default styles;
