import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {flex: 1},
  header: {
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 6,
    paddingHorizontal: 4,
  },
  summaryText: {flex: 1, fontSize: 12, lineHeight: 17},
  updateText: {fontSize: 11, lineHeight: 16},
  helperText: {marginTop: 3, paddingHorizontal: 4, fontSize: 10, lineHeight: 15},
  legend: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
    marginTop: 8,
    paddingHorizontal: 4,
  },
  legendItem: {flexDirection: 'row', alignItems: 'center', gap: 6},
  legendDot: {width: 9, height: 9, borderRadius: 5},
  legendText: {fontSize: 10, lineHeight: 15},
  inlineError: {marginTop: 7, paddingHorizontal: 4, fontSize: 11, lineHeight: 16},
  mapContainer: {flex: 1},
  map: {flex: 1},
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
  },
  stateTitle: {fontSize: 16, lineHeight: 22, fontWeight: '700', textAlign: 'center'},
  stateText: {marginTop: 7, fontSize: 13, lineHeight: 19, textAlign: 'center'},
  retryButton: {marginTop: 16, paddingHorizontal: 18, paddingVertical: 10, borderRadius: 10},
  retryText: {fontSize: 13, lineHeight: 18, fontWeight: '700'},
  marker: {
    minWidth: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
    borderWidth: 2,
    borderRadius: 17,
  },
  markerText: {fontSize: 10, lineHeight: 14, fontWeight: '800'},
  overlay: {
    position: 'absolute',
    left: 16,
    right: 16,
    top: 16,
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderRadius: 10,
    borderWidth: StyleSheet.hairlineWidth,
  },
  overlayTitle: {fontSize: 13, lineHeight: 18, fontWeight: '700'},
  overlayText: {marginTop: 2, fontSize: 11, lineHeight: 16},
});

export default styles;
