import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {flex: 1},
  listContent: {paddingHorizontal: 16, paddingTop: 16, paddingBottom: 28},
  moduleHeader: {},
  instructions: {marginTop: 13, fontSize: 12, lineHeight: 18},
  searchRow: {height: 44, flexDirection: 'row', gap: 8, marginTop: 14},
  searchInput: {
    flex: 1,
    height: 44,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderRadius: 10,
    fontSize: 12,
  },
  searchButton: {
    height: 44,
    justifyContent: 'center',
    paddingHorizontal: 15,
    borderRadius: 10,
  },
  searchButtonText: {fontSize: 12, lineHeight: 17, fontWeight: '700'},
  inlineLoading: {marginTop: 10},
  inlineError: {paddingTop: 10},
  inlineErrorText: {fontSize: 12, lineHeight: 17},
  listHeading: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 22,
    marginBottom: 9,
  },
  sectionTitle: {fontSize: 15, lineHeight: 21, fontWeight: '700'},
  sectionAside: {fontSize: 11, lineHeight: 16},
  userRow: {
    minHeight: 72,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 13,
    paddingVertical: 11,
    borderWidth: 1,
    borderRadius: 11,
    marginBottom: 8,
  },
  userIdentity: {flex: 1, minWidth: 0},
  userName: {fontSize: 14, lineHeight: 19, fontWeight: '700'},
  userMeta: {marginTop: 2, fontSize: 11, lineHeight: 16},
  userState: {marginTop: 3, fontSize: 10, lineHeight: 14, fontWeight: '600'},
  userAction: {fontSize: 11, lineHeight: 16, fontWeight: '700'},
  state: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    paddingVertical: 48,
  },
  stateTitle: {fontSize: 16, lineHeight: 22, fontWeight: '700', textAlign: 'center'},
  stateText: {marginTop: 6, fontSize: 13, lineHeight: 19, textAlign: 'center'},
  retryButton: {marginTop: 16, paddingHorizontal: 18, paddingVertical: 10, borderRadius: 10},
  retryButtonText: {fontSize: 13, lineHeight: 18, fontWeight: '700'},
  loadingFooter: {paddingVertical: 18},
  modal: {flex: 1, justifyContent: 'flex-end'},
  backdrop: {...StyleSheet.absoluteFillObject},
  resetSheet: {
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    paddingHorizontal: 18,
    paddingTop: 9,
  },
  sheetHandle: {alignSelf: 'center', width: 40, height: 4, borderRadius: 2},
  sheetTitle: {marginTop: 16, fontSize: 18, lineHeight: 24, fontWeight: '700'},
  sheetDescription: {marginTop: 5, fontSize: 13, lineHeight: 19},
  blockedNotice: {marginTop: 10, fontSize: 12, lineHeight: 17, fontWeight: '600'},
  sheetActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
    marginTop: 20,
  },
  cancelButton: {paddingHorizontal: 12, paddingVertical: 12},
  cancelButtonText: {fontSize: 13, lineHeight: 18, fontWeight: '600'},
  confirmButton: {paddingHorizontal: 16, paddingVertical: 12, borderRadius: 10},
  confirmButtonText: {fontSize: 13, lineHeight: 18, fontWeight: '700'},
});

export default styles;
