import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {flex: 1},
  listContent: {paddingHorizontal: 16, paddingTop: 16, paddingBottom: 28},
  emptyListContent: {flexGrow: 1},

  moduleHeader: {marginBottom: 14},
  stateBackHeader: {paddingHorizontal: 16, paddingTop: 16},

  appliedFilters: {
    minHeight: 70,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingHorizontal: 13,
    paddingVertical: 10,
    borderWidth: 1,
    borderRadius: 11,
  },
  appliedFiltersContent: {flex: 1, minWidth: 0},
  appliedFiltersLabel: {fontSize: 10, lineHeight: 14},
  appliedFiltersPeriod: {marginTop: 1, fontSize: 13, lineHeight: 18, fontWeight: '700'},
  appliedFiltersMeta: {marginTop: 2, fontSize: 10, lineHeight: 14},
  appliedFiltersAction: {fontSize: 12, lineHeight: 17, fontWeight: '700'},
  adminDateRow: {flexDirection: 'row', gap: 8},
  adminDateField: {
    flex: 1,
    height: 49,
    justifyContent: 'center',
    paddingHorizontal: 12,
    borderWidth: 1,
    borderRadius: 10,
  },
  adminDateLabel: {fontSize: 10, lineHeight: 14},
  adminDateValue: {marginTop: 1, fontSize: 13, lineHeight: 18, fontWeight: '600'},
  periodShortcuts: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 18,
    marginTop: 7,
  },
  periodShortcut: {paddingVertical: 2},
  periodShortcutText: {fontSize: 11, lineHeight: 16, fontWeight: '600'},
  searchInput: {
    height: 44,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderRadius: 10,
    fontSize: 12,
  },
  collaboratorSelector: {
    height: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderRadius: 10,
  },
  collaboratorSelectorValue: {flex: 1, fontSize: 12, lineHeight: 17, fontWeight: '600'},
  collaboratorSelectorAction: {fontSize: 11, lineHeight: 16, fontWeight: '700'},
  collaboratorSheet: {height: '82%'},
  collaboratorSelectorScreen: {flex: 1},
  collaboratorListContent: {paddingTop: 8, paddingBottom: 10},
  collaboratorListItem: {
    minHeight: 43,
    justifyContent: 'center',
    paddingHorizontal: 11,
    paddingVertical: 5,
    borderRadius: 8,
  },
  collaboratorName: {fontSize: 12, lineHeight: 17, fontWeight: '600'},
  collaboratorSector: {marginTop: 1, fontSize: 10, lineHeight: 14},
  collaboratorListState: {alignItems: 'center', paddingHorizontal: 16, paddingVertical: 28},
  collaboratorStateText: {fontSize: 12, lineHeight: 18, textAlign: 'center'},
  collaboratorListFooter: {paddingVertical: 14},
  filterLoading: {marginTop: 10},
  inlineError: {paddingVertical: 10},
  inlineErrorText: {fontSize: 12, lineHeight: 17},

  filterSheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingVertical: 15,
  },
  filterSheetClose: {fontSize: 12, lineHeight: 17, fontWeight: '700'},
  filterSheetContent: {paddingBottom: 4},
  filterSection: {marginBottom: 20},
  filterSectionLabel: {marginBottom: 8, fontSize: 12, lineHeight: 17, fontWeight: '700'},
  filterResultOptions: {gap: 7},
  filterResultOption: {
    minHeight: 42,
    justifyContent: 'center',
    paddingHorizontal: 12,
    borderWidth: 1,
    borderRadius: 9,
  },
  filterResultOptionText: {fontSize: 12, lineHeight: 17, fontWeight: '600'},
  filterSheetActions: {flexDirection: 'row', gap: 8, paddingTop: 10},
  clearFiltersButton: {
    width: 88,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderRadius: 10,
  },
  clearFiltersText: {fontSize: 12, lineHeight: 17, fontWeight: '700'},
  applyFiltersButton: {
    flex: 1,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  applyFiltersText: {fontSize: 12, lineHeight: 17, fontWeight: '700'},

  summarySection: {marginTop: 18},
  sectionHeading: {
    minHeight: 28,
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 8,
  },
  sectionTitle: {fontSize: 15, lineHeight: 21, fontWeight: '700'},
  sectionAside: {fontSize: 11, lineHeight: 16, textAlign: 'right'},
  summaryCard: {padding: 12, borderWidth: 1, borderRadius: 12},
  mainMetricsRow: {flexDirection: 'row'},
  mainMetric: {flex: 1, paddingRight: 6},
  mainMetricValue: {fontSize: 19, lineHeight: 24, fontWeight: '700'},
  mainMetricLabel: {marginTop: 2, fontSize: 10, lineHeight: 14},
  summaryDivider: {height: StyleSheet.hairlineWidth, marginVertical: 11},
  summaryLine: {fontSize: 11, lineHeight: 17},
  limitText: {marginTop: 6, fontSize: 10, lineHeight: 15},

  listHeading: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 22,
    marginBottom: 2,
  },
  routeCard: {
    paddingHorizontal: 13,
    paddingVertical: 12,
    borderWidth: 1,
    borderRadius: 12,
    marginBottom: 9,
  },
  routeHeader: {flexDirection: 'row', alignItems: 'flex-start', gap: 10},
  routeIdentity: {flex: 1, minWidth: 0},
  routeUsername: {fontSize: 14, lineHeight: 19, fontWeight: '700'},
  routeMeta: {marginTop: 1, fontSize: 11, lineHeight: 16},
  routeStatusBox: {
    alignSelf: 'flex-start',
    marginTop: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 7,
  },
  routeStatus: {fontSize: 11, lineHeight: 16, fontWeight: '600'},
  routeOrigin: {marginTop: 9, fontSize: 11, lineHeight: 16},
  routeSummary: {marginTop: 2, fontSize: 12, lineHeight: 17, fontWeight: '600'},
  routeTripSummary: {marginTop: 1, fontSize: 11, lineHeight: 16},
  routeEvidence: {marginTop: 5, fontSize: 10, lineHeight: 15, fontWeight: '600'},

  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    paddingVertical: 48,
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    paddingVertical: 48,
  },
  stateTitle: {fontSize: 16, lineHeight: 22, fontWeight: '700', textAlign: 'center'},
  stateDescription: {marginTop: 6, fontSize: 13, lineHeight: 19, textAlign: 'center'},
  retryButton: {marginTop: 16, paddingHorizontal: 18, paddingVertical: 10, borderRadius: 10},
  retryText: {fontSize: 13, lineHeight: 18, fontWeight: '700'},
  loadingFooter: {paddingVertical: 18},

  modal: {flex: 1, justifyContent: 'flex-end'},
  backdrop: {...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0, 0, 0, 0.46)'},
  filterSheet: {
    maxHeight: '92%',
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    paddingHorizontal: 16,
    paddingTop: 9,
  },
  filterSheetTitle: {fontSize: 17, lineHeight: 23, fontWeight: '700'},

  sheet: {
    maxHeight: '86%',
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    paddingHorizontal: 18,
    paddingTop: 10,
  },
  sheetHandle: {alignSelf: 'center', width: 40, height: 4, borderRadius: 2},
  sheetHeader: {marginTop: 16, marginBottom: 14},
  sheetTitle: {fontSize: 18, lineHeight: 24, fontWeight: '700'},
  sheetSubtitle: {marginTop: 3, fontSize: 12, lineHeight: 17},
  detailSummary: {padding: 13, borderRadius: 11, marginBottom: 18},
  detailSummaryTitle: {fontSize: 13, lineHeight: 18, fontWeight: '700'},
  detailSummaryText: {marginTop: 4, fontSize: 12, lineHeight: 18},
  detailSection: {marginBottom: 18},
  detailSectionTitle: {fontSize: 13, lineHeight: 18, fontWeight: '700', marginBottom: 6},
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 18,
    paddingVertical: 6,
  },
  detailLabel: {flex: 1, fontSize: 12, lineHeight: 17},
  detailValue: {flex: 1.2, fontSize: 12, lineHeight: 17, fontWeight: '600', textAlign: 'right'},
  detailNotice: {fontSize: 11, lineHeight: 16, marginTop: 5},
  destination: {paddingVertical: 8, borderBottomWidth: StyleSheet.hairlineWidth},
  destinationTitle: {fontSize: 12, lineHeight: 17, fontWeight: '700'},
  destinationMeta: {marginTop: 2, fontSize: 11, lineHeight: 16},
  detailActions: {gap: 8, marginTop: 4},
  mapButton: {alignItems: 'center', paddingVertical: 12, borderWidth: 1, borderRadius: 10},
  mapButtonText: {fontSize: 13, lineHeight: 18, fontWeight: '700'},
  closeButton: {alignItems: 'center', paddingVertical: 13, borderRadius: 10},
  closeButtonText: {fontSize: 14, lineHeight: 19, fontWeight: '700'},
});

export default styles;
