import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  fabContainer: {
    position: 'absolute',
    right: 14,
    top: '54%',
    width: 52,
    height: 52,
    zIndex: 50,
    elevation: 12,
  },
  fab: {
    width: 52,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 26,
    borderWidth: 1,
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.22,
    shadowRadius: 7,
    elevation: 8,
  },
  contextHint: {
    position: 'absolute',
    right: 60,
    top: -8,
    width: 224,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderRadius: 12,
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 7,
  },
  contextHintText: {
    fontSize: 13,
    lineHeight: 18,
  },
  contextHintAction: {
    marginTop: 4,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
  },
  keyboardAvoiding: {
    width: '100%',
    justifyContent: 'flex-end',
  },
  modalRoot: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.42)',
  },
  panel: {
    width: '100%',
    maxHeight: '86%',
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    overflow: 'hidden',
  },
  handle: {
    width: 38,
    height: 4,
    alignSelf: 'center',
    marginTop: 8,
    borderRadius: 2,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 8,
  },
  headerText: {
    flex: 1,
  },
  title: {
    fontSize: 17,
    lineHeight: 22,
    fontWeight: '700',
  },
  subtitle: {
    marginTop: 1,
    fontSize: 12,
    lineHeight: 16,
  },
  closeButton: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scroll: {
    flexShrink: 1,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  onboardingCard: {
    marginBottom: 12,
    padding: 13,
    borderWidth: 1,
    borderRadius: 12,
  },
  onboardingTitle: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  onboardingDescription: {
    marginTop: 3,
    marginBottom: 9,
    fontSize: 12,
    lineHeight: 17,
  },
  onboardingExample: {
    minHeight: 38,
    justifyContent: 'center',
    marginTop: 6,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderRadius: 9,
  },
  onboardingExampleText: {
    fontSize: 12,
    lineHeight: 17,
  },
  onboardingClose: {
    alignSelf: 'flex-end',
    marginTop: 10,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  onboardingCloseText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
  },
  heardLabel: {
    marginBottom: 4,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  transcript: {
    marginBottom: 10,
    fontSize: 13,
    lineHeight: 18,
    fontStyle: 'italic',
  },
  responseCard: {
    paddingHorizontal: 12,
    paddingVertical: 11,
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 10,
  },
  responseRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  responseLoader: {
    marginRight: 9,
  },
  responseText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
  },
  listenButton: {
    alignSelf: 'flex-end',
    paddingHorizontal: 6,
    paddingVertical: 7,
  },
  listenButtonText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
  },
  inputRow: {
    minHeight: 46,
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 12,
    paddingRight: 5,
    borderWidth: 1,
    borderRadius: 12,
  },
  textInput: {
    flex: 1,
    minHeight: 42,
    paddingVertical: 8,
    paddingRight: 8,
    fontSize: 13,
  },
  sendButton: {
    minWidth: 64,
    minHeight: 36,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    borderRadius: 9,
  },
  sendButtonText: {
    fontSize: 12,
    fontWeight: '700',
  },
  sectionTitle: {
    marginTop: 16,
    marginBottom: 8,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
  },
  chipsScroll: {
    marginHorizontal: -16,
  },
  chips: {
    gap: 8,
    paddingHorizontal: 16,
  },
  chip: {
    flexShrink: 0,
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 11,
    borderWidth: 1,
    borderRadius: 19,
  },
  chipText: {
    marginLeft: 6,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
  },
  dynamicChipText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
  },
  voicePreference: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    paddingHorizontal: 2,
    paddingVertical: 6,
  },
  voicePreferenceText: {
    flex: 1,
    paddingRight: 12,
  },
  voicePreferenceTitle: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  microphoneArea: {
    alignItems: 'center',
    paddingTop: 12,
  },
  microphoneButton: {
    width: 52,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 26,
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.18,
    shadowRadius: 6,
    elevation: 5,
  },
  microphoneHint: {
    marginTop: 7,
    fontSize: 12,
    lineHeight: 16,
    textAlign: 'center',
  },
});

export default styles;
